# Generated by Django 5.2.6 on 2025-09-27 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdate',
            name='author',
            field=models.CharField(default='Неизвестен', max_length=100),
        ),
        migrations.AlterField(
            model_name='newsdate',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='newsdate',
            name='main_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='newsdate',
            name='save_peaple_id',
            field=models.CharField(default='parser', max_length=100),
        ),
        migrations.AlterField(
            model_name='newsdate',
            name='source',
            field=models.CharField(default='mk.ru', max_length=200),
        ),
        migrations.AlterField(
            model_name='newsdate',
            name='topic',
            field=models.CharField(default='general', max_length=100),
        ),
        migrations.AlterField(
            model_name='newsdate',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
