# Generated by Django 5.2.6 on 2025-09-27 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_newsdate_author_alter_newsdate_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsdate',
            name='author',
            field=models.CharField(default='Неизвестен', max_length=500),
        ),
    ]
