# Generated by Django 5.2.6 on 2025-09-27 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsDate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500, unique=True)),
                ('image_url', models.CharField(max_length=500)),
                ('main_text', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('source', models.CharField(max_length=200)),
                ('views', models.IntegerField()),
                ('topic', models.CharField(max_length=100)),
                ('save_peaple_id', models.CharField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mail', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=500)),
                ('news_ids', models.CharField()),
            ],
        ),
    ]
