# Generated by Django 5.2.6 on 2025-10-09 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_alter_newsdate_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_news', to='news.newsdate')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SaveNews',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_news', to='news.newsdate')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='save_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VeiwsNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_news', to='news.newsdate')),
                ('users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='UserNews',
        ),
    ]
