# Generated by Django 5.2.6 on 2025-10-09 16:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_likenews_savenews_veiwsnews_delete_usernews'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='likenews',
            unique_together={('users', 'news')},
        ),
        migrations.AlterUniqueTogether(
            name='veiwsnews',
            unique_together={('users', 'news')},
        ),
    ]
