# Generated by Django 5.2.6 on 2025-10-17 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_likenews_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdate',
            name='likes',
            field=models.IntegerField(default=701),
        ),
        migrations.AlterField(
            model_name='newsdate',
            name='views',
            field=models.IntegerField(default=906),
        ),
    ]
